services:
  alephium:
    image: alephium/alephium:v3.6.2
    restart: 'no'
    ports:
      - 19973:19973/tcp
      - 19973:19973/udp
      - 127.0.0.1:10973:10973
      - 127.0.0.1:11973:11973
      - 127.0.0.1:12973:12973
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./user.conf:/alephium-home/.alephium/user.conf
      # - ~/.alephium:/alephium-home/.alephium
    environment:
      ALEPHIUM_FILE_LOG_LEVEL: 'DEBUG'
    healthcheck:
      test: ['CMD', 'curl', 'http://127.0.0.1:12973/infos/self-clique']
      timeout: 45s

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-explorer}
      PGDATA: /data/postgres
    ports:
      - '127.0.0.1:19974:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      timeout: 45s
      interval: 10s

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - '${PGADMIN_PORT:-5050}:80'
    restart: unless-stopped

  explorer-backend:
    image: alephium/explorer-backend:v1.19.1
    depends_on:
      postgres:
        condition: service_healthy
      alephium:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 9090:9090
    security_opt:
      - no-new-privileges:true
    environment:
      - EXPLORER_HOST=0.0.0.0
      - EXPLORER_PORT=9090
      - BLOCKFLOW_HOST=alephium
      - BLOCKFLOW_PORT=12973
      - BLOCKFLOW_NETWORK_ID=7
      # - ALEPHIUM_API_KEY=0000000000000000000000000000000000000000000000000000000000000000
      - DB_NAME=${POSTGRES_DB:-explorer}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  explorer-frontend:
    image: alephium/explorer:1.9.4
    depends_on:
      - explorer-backend
    restart: 'no'
    ports:
      - 3000:3000
    security_opt:
      - no-new-privileges:true
    environment:
      - VITE_NODE_URL=http://localhost:12973
      - VITE_BACKEND_URL=http://localhost:9090
      - VITE_NETWORK_TYPE=testnet

  # grafana:
  #   image: grafana/grafana:7.2.1
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./grafana/provisioning/:/etc/grafana/provisioning
  #   env_file:
  #     - ./grafana/config.monitoring
  #   restart: unless-stopped

  # prometheus:
  #   image: prom/prometheus:v2.21.0
  #   depends_on:
  #     - alephium
  #     - explorer-backend
  #   volumes:
  #     - ./prometheus/:/etc/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--web.console.libraries=/usr/share/prometheus/console_libraries"
  #     - "--web.console.templates=/usr/share/prometheus/consoles"
  #   restart: unless-stopped
